apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp

helmGlobals:
  chartHome: ../../chart

helmCharts:
  - name: chart
    releaseName: myapp
    namespace: myapp
    version: 0.1.0
    valuesInline:
      replicaCount: 2
      image:
        tag: "3a67d82"
