apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp

helmGlobals:
  chartHome: ../../

helmCharts:
  - name: chart
    releaseName: myapp
    namespace: myapp
    version: 0.1.0
    valuesInline:
      replicaCount: 2
      image:
        tag: dev
