apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

helmGlobals:
  chartHome: ../../

helmCharts:
  - name: chart
    releaseName: myapp
    namespace: myapp
    valuesInline:
      image:
        tag: "3a67d82"
