apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp

helmGlobals:
  chartHome: ../../

helmCharts:
  - name: myapp
    releaseName: myapp
    namespace: myapp
    valuesInline:
      replicaCount: 2
      image:
        tag: staging