apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 58.7.2
    releaseName: kube-prom
    namespace: observability
    valuesFile: helm-values/kube-prometheus-stack.values.yaml

  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: 2.10.2
    releaseName: loki
    namespace: observability
    valuesFile: helm-values/loki.values.yaml
