name: Build Push and PR

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "src/Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    env:
      REGION: europe-west1
      PROJECT_ID: project-40cabc90-4d22-4606-b51
      REPO: my-docker
      IMAGE: myapp

    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/903685462877/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-ci@project-40cabc90-4d22-4606-b51.iam.gserviceaccount.com"
          create_credentials_file: false
      
      - name: Export Google credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_GHA_CREDS_PATH" >> $GITHUB_ENV

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and push image
        run: |
          TAG=${GITHUB_SHA::7}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          IMAGE_URI=europe-west1-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}:${TAG}
          docker build -f src/Dockerfile -t ${IMAGE_URI} .
          docker push ${IMAGE_URI}

      - name: Update dev overlay tag
        run: |
          sed -i "s/tag: \".*\"/tag: \"${TAG}\"/" apps/myapp/overlays/dev/kustomization.yaml

      - name: Disable GCP credential file export
        run: |
          unset GOOGLE_APPLICATION_CREDENTIALS
          unset CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
          unset GOOGLE_GHA_CREDS_PATH


      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: deploy myapp:${{ env.TAG }} to dev"
          title: "Deploy myapp:${{ env.TAG }} to dev"
          body: "Automated image update for dev environment."
          branch: "deploy/dev-${{ env.TAG }}"
          add-paths: "apps/myapp/overlays/dev/kustomization.yaml"
